site_name: Crosschain Risk Framework
strict: true
# For documentation on the mkdocs configuration see:
# mkdocs: https://www.mkdocs.org/user-guide/configuration/
# Material theme: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
repo_url: https://github.com/CrosschainRiskFramework/CrosschainRiskFramework.github.io
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.expand
    - navigation.tracking
    - toc.integrate
    - toc.follow
plugins:
  - include-markdown
  - search
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
nav:
  - Introduction: "framework/01intro/introduction.md"
  - Categories of Risk: "framework/20categories/categories-of-risk.md"
  - Network Consensus Risk: "framework/20categories/10network/network.md"
  - Protocol Architecture Risk: "framework/20categories/20architecture/architecture.md"
  - Protocol Implementation Risk: "framework/20categories/30implementation/protocol-implementation-risk.md"
  - Protocol Operational Risk: "framework/20categories/40operation/protocol-operation-risk.md"
  - Risk Scoring: "framework/30scoring/scoring.md"
  - Contributions: "authors/contributions.md"
  - FAQ: "faq/faq.md"
  - References: "reference/ref.md"


# Provide access to emojis, used for the authors page:
# https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
