site_name: Crosschain Risk Framework

# For documentation on the mkdocs configuration see:
# mkdocs: https://www.mkdocs.org/user-guide/configuration/
# Material theme: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
theme:
  name: material
  features:
    - navigation.expand
    - toc.integrate
    - toc.follow
plugins:
  - include-markdown
  - search
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
nav:
  - Introduction: "framework/01intro/introduction.md"
  - Stakeholders of Crosschain: "framework/10stakeholders/stakeholders.md"
  - Sources of Risk: "framework/20sources/sources-of-risk.md"
  - Comparison: "comparison/comparison.md"
  - Contributions: "authors/contributions.md"
  - FAQ: "faq/faq.md"
  - Reference: "reference/ref.md"


# Provide access to emojis, used for the authors page:
# https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
